project_name: Multi-Agent AI Collaboration Interface

agents:
  - name: agent_a
    type: GPTAgent
    role: Инициатор
    path: agents/gpt_agent.py

  - name: agent_b
    type: CopilotAgent
    role: Структурный помощник
    path: agents/copilot_agent.py

  - name: agent_c
    type: CriticAgent
    role: Оценщик
    path: agents/critic_agent.py

router:
  type: basic
  logic: sequential

memory:
  enabled: true
  type: ephemeral
